import Head from "next/head";
import React from "react";
import ProductsTemplate from "src/templates/products";

export default function ProductsByGender() {
	return (
		<>
			<Head>
				<title>Women products - Eshop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ProductsTemplate gender="women" />
		</>
	);
}
