import Head from "next/head";
import React from "react";
import { useAuth } from "src/components/authProvider";
import cookie from "cookie";
import AccountTemplate from "src/templates/account";

export default function AccountPage({}) {
	const { redirectIfNotLogged } = useAuth();

	// redirectIfNotLogged("/");

	return (
		<>
			<Head>
				<title>Account - Eshop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<AccountTemplate />
		</>
	);
}

export async function getServerSideProps(context) {
	const { req, res } = context;
	const cookies = cookie.parse(req.headers.cookie || "");

	if (!cookies.auth) {
		res.writeHead(302, { Location: "/sign-in" });
		res.end();
	}

	return { props: {} };
}
