import Head from "next/head";
import React from "react";
import { useAuth } from "src/components/authProvider";
import CreateAccountTemplate from "src/templates/createAccount";

export default function CreateAccount() {
	const { redirectIfLogged } = useAuth();

	redirectIfLogged("/");

	return (
		<>
			<Head>
				<title>Create Account - Eshop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CreateAccountTemplate />
		</>
	);
}
