import Head from "next/head";
import React from "react";
import cookie from "cookie";
import CreateAccountTemplate from "src/templates/createAccount";

export default function CreateAccount() {
	return (
		<>
			<Head>
				<title>Create Account - Eshop</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CreateAccountTemplate />
		</>
	);
}

export async function getServerSideProps(context) {
	const { req, res } = context;
	const cookies = cookie.parse(req.headers.cookie || "");

	if (cookies.auth) {
		res.writeHead(302, { Location: "/" });
		res.end();
		return;
	}

	return { props: {} };
}
